[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "numpy>=2.3.0",
    "opencv-python>=4.11.0.86",
    "pyserial>=3.5",
    "serial>=0.0.97",
    "setuptools>=80.9.0",
]
